"""Add scheduled_date and end_date to installations

Revision ID: 0f7e077dd948
Revises: fae868974514
Create Date: 2025-09-14 18:41:20.664012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7e077dd948'
down_revision = 'fae868974514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('scheduled_date')

    # ### end Alembic commands ###
